server:
  port: 8081

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: medecin-service
          uri: http://localhost:8089
          predicates:
            - Path=/medecins/**
        - id: patient-service
          uri: lb://PATIENT
          predicates:
            - Path=/patients/**

      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
