server:
  port: 8081

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: medecin-service
          uri: http://localhost:8089
          predicates:
            - Path=/medecins/**

        - id: patient-service
          uri: http://localhost:9090
          predicates:
            - Path=/patients/**

logging:
  level:
    org.springframework: DEBUG

    #spring.cloud.gateway.discovery.locator.enabled=true dynamique
